name: booking_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  geolocator: ^9.0.1
  http: ^0.13.5
  flutter_bloc: ^8.1.1
  intl: ^0.17.0
  font_awesome_flutter: ^10.2.1
  country_picker: ^2.0.16
  rx_shared_preferences: ^3.0.0
  conditional_builder_null_safety: ^0.0.6
  badges: ^2.0.3
  carousel_slider: ^4.1.1
  image_stack: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf

